---
title: "Sandbox"
output: html_document
---

#reactive
#fonts
#image size (750 as the height?)
#placement of text below?

Things to alter
-color of text boxes (geom_rect --> size dependent on #letters) - one color for the text box color (gradient hex) - text inside gonna be white
-what the text says - 3 different textboxes (filename)
-background/input image?
-effect on the image??


```{r packages}
library(tidyverse)
library(cowplot)
library(magick)
```

```{r inputs}
path <- "https://www.thebroad.org/sites/default/files/art/greenfieldsanders_kruger.jpeg"

#text
top <- "Your body"
middle <- "is a"
bottom <- "battleground"
text_size <- 10
rect_color <- "red"
text_color <- "white"
font <- "times"
emphasis <- "bold"

#0 to 5
border_size <- 10
#0 to 200
img_brightness <- 100
img_saturation <- 100
img_hue <- 100
```

```{r dimensions}
my_image <- image_read(path)

height <- image_info(my_image)$height
width <- image_info(my_image)$width

plot_size <- tribble(
  ~x, ~y,
  0, 0, 
  width, height)

if (height>width) {
size = width/500
} else {
size  = height/500
}
```

```{r labels}
#unsure of correct ratio for borders
label_maker <- tribble(
  ~text, ~x, ~y,
  top, width/2, height-30*size,
  middle, width/2, height/2,
  bottom, width/2, 30*size)
```

```{r plotting}
ggplot() +
  geom_point(data = plot_size, aes(x = x, y = y), alpha = 0) +
    geom_rect(aes(xmin = 0, xmax = width,
            ymin = 0, ymax = height),
            color = rect_color,
            size = border_size,
            fill = NA) +
  draw_image(image_modulate(my_image, 
               brightness = img_brightness, 
               saturation = img_saturation, 
               hue = img_hue), x = 0, y=0, width = width,  height = height) +
  geom_label(data = label_maker, 
             mapping = aes(x = x, 
                           y = y, 
                           label = text),
             size = text_size,
             fill = rect_color,
             color = text_color,
             family = font,
             fontface = emphasis,
             label.size = 0,
             label.r = unit(0, "lines")) +
  coord_equal() +
  theme_void()
```
