---
title: "R Notebook"
output: html_notebook
--- 

```{r}
library(tidyverse)
library(Rcpp)
library(reshape2)
library(colourlovers)
library(cowplot)
library(generativeart) # https://github.com/cutterkom/generativeart
```

```{r}
# set the paths
IMG_DIR <- "img/"
IMG_SUBDIR <- "everything/"
IMG_SUBDIR2 <- "handpicked/"
IMG_PATH <- paste0(IMG_DIR, IMG_SUBDIR)

LOGFILE_DIR <- "logfile/"
LOGFILE <- "logfile.csv"
LOGFILE_PATH <- paste0(LOGFILE_DIR, LOGFILE)

# create the directory structure
generativeart::setup_directories(IMG_DIR, IMG_SUBDIR, IMG_SUBDIR2, LOGFILE_DIR)
```


```{r}
my_formula <- list(
  x = quote(runif(1, -1, 10) * x_i^2 - sin(y_i^2)),
  y = quote(runif(1, -1, 10) * y_i^3 - cos(x_i^2) * y_i^2)
)

generativeart::generate_img(formula = my_formula, 
                            nr_of_img = 1, 
                            polar = TRUE, 
                            color = alpha("black", 0.5), 
                            background_color = "white")

last_plot()
```

```{r}

my_formula <- list(
  x = quote(runif(1, -1, 10) * x_i^2 - sin(y_i^2)),
  y = quote(runif(1, -1, 10) * y_i^3 - cos(x_i^2) * y_i^4)
)

fin <- generativeart::generate_img(formula = my_formula, 
                            nr_of_img = 1, 
                            polar = TRUE, 
                            color = alpha("black", 0.5), 
                            background_color = "white")

fing <- last_plot()

fing

```

