---
title: "plot-mockup"
author: "Lillian Clark"
date: "11/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggforce)
library(ggnewscale)
```

```{r}
circles <- tribble(~x, ~y, ~shape, ~color, ~radius, ~layer_order, ~color_category,
                30, 69, "fill", "#583B76", 6, 1, "purple",
                30, 69, "fill", "#0F0F11", 12, 2, "black",
                30, 69, "fill", "#CA7A7C", 14, 4, "pink",
                30, 69, "fill", "#CB6A5A", 15, 5, "red",
                39, 57, "fill", "#A42117", 5, 3, "red",
                39.5, 56.5, "fill", "#E2BF50", 7.5, 6, "yellow",
                27, 25, "fill", "#CCB644", 4.5, 1, "yellow",
                27, 25, "stroke", "#0C0E18", 4.7, 2, "black",
                27, 25, "fill", "#6E93B6", 6, 3, "blue",
                27, 25, "fill", "#9E98B2", 7.3, 4, "purple",
                62, 11.5, "fill", "#2F5581", 3.2, 1, "blue",
                62.5, 11, "fill", "#D4A590", 4.5, 2, "orange",
                62.5, 11, "fill", "#CEBF4A", 5.5, 3, "yellow",
                121, 14, "fill", "#73776D", 5.5, 1, "grey",
                106.5, 20, "fill", "#7F67A8", 3.5, 1, "purple",
                75.5, 60, "fill", "#F7F4F5", 2.2, 1, "white",
                75.5, 60, "stroke", "#701A23", 2.5, 2, "red",
                75.5, 60, "stroke", "#010601", 3, 3, "black",
                75.5, 60, "fill", "#F5F0F3", 4.3, 4, "white",
                75.5, 60, "stroke", "#A19E9B", 4.4, 5, "black",
                75.5, 69, "fill", "#BB3247", 1, 1, "red",
                75.5, 69, "stroke", "#202222", 1.2, 2, "black",
                82, 78, "fill", "#80808C", 1.5, 1, "grey",
                88, 65, "fill", "#FFFEFD", 1.5, 1, "white",
                88, 65, "stroke", "#666561", 1.7, 2, "grey",
                88, 65, "fill", "#B3BBB2", 0.8, 3, "green",
                96, 73.5, "fill", "#2A2981", 1.3, 1, "blue",
                96, 73.5, "fill", "#CBC5C0", 1.8, 2, "grey",
                96, 73.5, "stroke", "#2E2A28", 2, 3, "black",
                113, 49, "fill", "#375A99", 4, 1, "blue",
                124, 63.5, "fill", "#A88698", 2.5, 1, "purple",
                124.3, 63.2, "fill", "#C64536", 2.9, 2, "red",
                124, 70.5, "fill", "#7697CF", 2.2, 1, "blue",
                124, 70.5, "fill", "#DDCC77", 2.8, 2, "yellow",
                132.5, 68.5, "fill", "#F2EDF1", 2, 1, "white",
                132.5, 68.5, "stroke", "#0C0908", 2.2, 2, "black",
                #this one is special and needs to actually be stroke
                109, 68, "stroke", "#080A08", 4.2, 3, "black",
                111, 68, "fill", "#95B29C", 3.5, 1, "green",
                109, 68, "fill", "#C7AC60", 4, 2, "yellow",
                97, 46, "fill", "#050405", 0.5, 1, "black",
                96.5, 46, "fill", "#E7DEDC", 3, 2, "white",
                96.5, 46, "fill", "#33388F", 3.7, 3, "blue",
                96.5, 46, "stroke", "#170E01", 3.9, 4, "black")

circle_1 <- circles %>%
  filter(layer_order == 1) %>%
  mutate(
    color_order = row_number(),
    color = fct_reorder(color, color_order))

cols1 <- as.character(circle_1$color)

circle_2 <- circles %>%
  filter(layer_order == 2) %>%
  mutate(
    color_order = row_number(),
    color = fct_reorder(color, color_order))

cols2 <- as.character(circle_2$color)

circle_3 <- circles %>%
  filter(layer_order == 3) %>%
  mutate(
    color_order = row_number(),
    color = fct_reorder(color, color_order))

cols3 <- as.character(circle_3$color)

circle_4 <- circles %>%
  filter(layer_order == 4) %>%
  mutate(
    color_order = row_number(),
    color = fct_reorder(color, color_order))

cols4 <- as.character(circle_4$color)

circle_5 <- circles %>%
  filter(layer_order == 5) %>%
  mutate(
    color_order = row_number(),
    color = fct_reorder(color, color_order))

cols5 <- as.character(circle_5$color)

circle_6 <- circles %>%
  filter(layer_order == 6) %>%
  mutate(
    color_order = row_number(),
    color = fct_reorder(color, color_order))

cols6 <- as.character(circle_6$color)

ggplot() +
  #geom_circle(data = circles, aes(x0 = x, y0 = y, r = radius, color = color)) +
  geom_circle(data = circle_6, aes(x0 = x, y0 = y, r = radius, fill = color, color = color)) +
  scale_fill_manual(values = cols6) +
  scale_color_manual(values = cols6) +
  new_scale_fill() +
  new_scale_color() +
  geom_circle(data = circle_5, aes(x0 = x, y0 = y, r = radius, fill = color, color = color)) +
  scale_fill_manual(values = cols5) +
  scale_color_manual(values = cols5) +
  new_scale_fill() +
  new_scale_color() +
  geom_circle(data = circle_4, aes(x0 = x, y0 = y, r = radius, fill = color, color = color)) +
  scale_fill_manual(values = cols4) +
  scale_color_manual(values = cols4) +
  new_scale_fill() +
  new_scale_color() +
  geom_circle(data = circle_3, aes(x0 = x, y0 = y, r = radius, fill = color, color = color)) +
  scale_fill_manual(values = cols3) +
  scale_color_manual(values = cols3) +
  new_scale_fill() +
  new_scale_color() +
  geom_circle(data = circle_2, aes(x0 = x, y0 = y, r = radius, fill = color, color = color)) +
  scale_fill_manual(values = cols2) +
  scale_color_manual(values = cols2) +
  new_scale_fill() +
  new_scale_color() +
  geom_circle(data = circle_1, aes(x0 = x, y0 = y, r = radius, fill = color, color = color)) +
  scale_fill_manual(values = cols1) +
  scale_color_manual(values = cols1) +
  coord_fixed(xlim = c(0, 157), ylim = c(0, 86), expand = FALSE) +
  guides(color = NULL) +
  theme_void() +
  theme(legend.position = "none",
        panel.background = element_rect(fill = "#D9D2BF"),
        plot.margin = unit(c(0, 0, 0, 0), units = "inches"))
```

